/*
package com.example.parkingfinder

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.material3.MaterialTheme
import com.example.parkingfinder.navigation.AppNavGraph
import com.google.firebase.FirebaseApp
import dagger.hilt.android.AndroidEntryPoint

@AndroidEntryPoint
class MainActivity : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        FirebaseApp.initializeApp(this)

        enableEdgeToEdge()
        setContent {
            MaterialTheme {
                AppNavGraph()
            }
        }
    }
}
*/

//the following will make use of the colour way as outlined in theme and colors instead of relying on Mateiral 3

//NOTE!! Majority of the code has been adopted and generated by GenAI, namely ChatGPT!!

package com.example.parkingfinder

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import com.example.parkingfinder.navigation.AppNavGraph
import com.example.parkingfinder.ui.theme.ParkingFinderTheme
import com.google.firebase.FirebaseApp
import dagger.hilt.android.AndroidEntryPoint

@AndroidEntryPoint
class MainActivity : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        FirebaseApp.initializeApp(this)

        enableEdgeToEdge()
        setContent {
            ParkingFinderTheme {
                AppNavGraph()
            }
        }
    }
}